// Autogenerated from Pigeon (v0.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LHStoredGlucoseSample;
@class LHStoredGlucoseResponse;
@class LHStoredGlucoseRequest;

@interface LHStoredGlucoseSample : NSObject
@property(nonatomic, strong, nullable) NSNumber * timestamp;
@property(nonatomic, strong, nullable) NSNumber * quantity;
@end

@interface LHStoredGlucoseResponse : NSObject
@property(nonatomic, strong, nullable) NSArray * serializedStoredGlucoseValues;
@end

@interface LHStoredGlucoseRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * startTimestamp;
@property(nonatomic, strong, nullable) NSNumber * endTimestamp;
@end

@interface LHCallbackApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)newSample:(LHStoredGlucoseSample*)input completion:(void(^)(NSError* _Nullable))completion;
@end
@protocol LHApi
-(void)listenForHealthData:(FlutterError *_Nullable *_Nonnull)error;
-(void)getGlucoseSamples:(nullable LHStoredGlucoseRequest *)input completion:(void(^)(LHStoredGlucoseResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void LHApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<LHApi> _Nullable api);

NS_ASSUME_NONNULL_END
