// Autogenerated from Pigeon (v0.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LHStoredGlucoseResponse;
@class LHStoredGlucoseRequest;

@interface LHStoredGlucoseResponse : NSObject
@property(nonatomic, strong, nullable) NSArray * serializedStoredGlucoseValues;
@end

@interface LHStoredGlucoseRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * startTimestamp;
@property(nonatomic, strong, nullable) NSNumber * endTimestamp;
@end

@protocol LHApi
-(void)getGlucoseSamples:(nullable LHStoredGlucoseRequest *)input completion:(void(^)(LHStoredGlucoseResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void LHApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<LHApi> _Nullable api);

NS_ASSUME_NONNULL_END
