// Autogenerated from Pigeon (v0.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/services.dart';

class StoredGlucoseSample {
  double? timestamp;
  int? quantity;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['timestamp'] = timestamp;
    pigeonMap['quantity'] = quantity;
    return pigeonMap;
  }

  static StoredGlucoseSample decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return StoredGlucoseSample()
      ..timestamp = pigeonMap['timestamp'] as double?
      ..quantity = pigeonMap['quantity'] as int?;
  }
}

class StoredGlucoseResponse {
  List<Object?>? serializedStoredGlucoseValues;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['serializedStoredGlucoseValues'] = serializedStoredGlucoseValues;
    return pigeonMap;
  }

  static StoredGlucoseResponse decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return StoredGlucoseResponse()
      ..serializedStoredGlucoseValues = pigeonMap['serializedStoredGlucoseValues'] as List<Object?>?;
  }
}

class StoredGlucoseRequest {
  double? startTimestamp;
  double? endTimestamp;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['startTimestamp'] = startTimestamp;
    pigeonMap['endTimestamp'] = endTimestamp;
    return pigeonMap;
  }

  static StoredGlucoseRequest decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return StoredGlucoseRequest()
      ..startTimestamp = pigeonMap['startTimestamp'] as double?
      ..endTimestamp = pigeonMap['endTimestamp'] as double?;
  }
}

abstract class CallbackApi {
  void newSample(StoredGlucoseSample arg);
  static void setup(CallbackApi? api) {
    {
      const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.CallbackApi.newSample', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.CallbackApi.newSample was null. Expected StoredGlucoseSample.');
          final StoredGlucoseSample input = StoredGlucoseSample.decode(message!);
          api.newSample(input);
          return;
        });
      }
    }
  }
}

class Api {
  /// Constructor for [Api].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  Api({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  Future<void> listenForHealthData() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.Api.listenForHealthData', const StandardMessageCodec(), binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<StoredGlucoseResponse> getGlucoseSamples(StoredGlucoseRequest arg) async {
    final Object encoded = arg.encode();
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.Api.getGlucoseSamples', const StandardMessageCodec(), binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(encoded) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return StoredGlucoseResponse.decode(replyMap['result']!);
    }
  }
}
